Cambly/syntax

.github/workflows/ci.yml
.github/workflows/release.yml

https://github.com/Cambly/syntax/actions/runs/4367246277/jobs/7638308860
```
sh: 1: turbo: not found
 ELIFECYCLE  Command failed.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
at m._setResult (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:7258)
at m.CheckComplete (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:6686)
at ChildProcess.<anonymous> (/home/runner/work/_actions/changesets/action/v1/dist/index.js:136:57[23](https://github.com/Cambly/syntax/actions/runs/4367246277/jobs/7638308860#step:5:24))
at ChildProcess.emit …
```

Internal: fix release part 2

---

.changeset/config.json
.changeset/smooth-rings-applaud.md

Noticed we had a `skip ci` in place which prevented CI from running the release

Internal: try with changeset - commit:false

---

.changeset/wet-suits-confess.md
packages/syntax-design-tokens/tokens/color/base.json

Thanks to @somethiiing for spotting this issue - we previously specced `#cbcbcb50` assuming it would be `rgba(203, 203, 203, 0.5)` but instead it was `rgba(203, 203, 203, 0.3)`.
Main issue is that the alpha channel (last 2 characters of the hex) is not the same as the opacity percentage

Internal: update gray10, gray30 and gray80 colors

---

.changeset/beige-donuts-allow.md
packages/syntax-core/src/Button/Button.tsx

`contextProps?.disabled` will be `false` by default. And in that case, we would never fall back to the second part `disabledProp`

Button: fix disabled prop

---

.changeset/spicy-eyes-fly.md
.vscode/settings.json
packages/syntax-core/src/Avatar/Avatar.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/ButtonGroup/ButtonGroup.tsx
packages/syntax-core/src/Heading/Heading.stories.tsx
packages/syntax-core/src/Heading/Heading.test.tsx
packages/syntax-core/src/Heading/Heading.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-core/src/Typography/Typography.test.tsx
packages/syntax-core/src/Typography/Typography.tsx
packages/syntax-core/src/colors/colors.module.css

* Adds `Typography` and `Heading` components to Syntax
Heading enforces a consistent style & accessibility best practices for headings.
* Sizes now go from small (100) to big (800) - previously the smallest size was `body300` which didn't make a lot of sense
* We now see `Typography` is the root component for all text to be rendered on Cambly. It allows for custom components such as `Heading` and has more flexibility built-in.

Typography & Heading: add components to Syntax

---

.github/workflows/ci.yml

Fixes an issue with https://github.com/Cambly/syntax/pull/73 where we added a dependency on `@cambly/syntax-design-tokens/dist` without it being built

Make lint and test job dependent on the build

---

apps/storybook/package.json
packages/syntax-core/package.json
packages/syntax-tsconfig/package.json
packages/syntax-utils/package.json
pnpm-lock.yaml

@nathan-ong  and @emmanuelgamboa09 noticed that using `composes` broke the `typescript-plugin-css-modules` plugin.
* Upgrade `typescript-plugin-css-modules` and TypeScript since that fixes the composes issue: https://github.com/mrmckeb/typescript-plugin-css-modules/issues/207
* Also had to upgrade `tsup` which added TS v5 support at https://github.com/egoist/tsup/releases/tag/v6.7.0

Internal: upgrade TypeScript to v5 & fix issue with "composes" in TypeScript plugin

---

.changeset/hungry-hairs-wonder.md
packages/syntax-core/src/Box/Box.module.css
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Box/margin.module.css
packages/syntax-core/src/Box/padding.module.css

* Add `display="none"`
* Fix responsive props
* Allow for `0` on props which take in numbers (e.g. margin and padding)
Noticed a bug with using `composes` where the outputted CSS didn't contain any CSS.
Before
After

Box: no longer use composes in media queries

---

.changeset/late-parrots-approve.md
packages/syntax-core/src/SelectList/SelectList.tsx
tsup.config.ts

After 2.2.0 we saw the following error in our frontend code:
```
2:27:18 PM next.1   |  error - /Users/christian/cambly/Cambly-Frontend/node_modules/@cambly/syntax-design-tokens/dist/js/index.js:6
2:27:18 PM next.1   |  export const ColorBaseBlack = "#000000";
2:27:18 PM next.1   |  ^^^^^^
2:27:18 PM next.1   |  SyntaxError: Unexpected token 'export'
```
**Issue**: @cambly/syntax-design-tokens used ES6 `export` statements which weren't supported
**Solution**: Inline @cambly/syntax-design-tokens constants

Internal: inline design system tokens to avoid unexpected token 'exports' error

---

.changeset/stupid-cows-travel.md
packages/syntax-core/src/Box/Box.module.css
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Box/Box.tsx

Previously we only had `pill` for rounding but that's confusing if you want to make something a circle:

Box: add rounding=circle

---

.changeset/lucky-cats-tell.md
packages/syntax-codemods/package.json
pnpm-lock.yaml

Otherwise we get the following exception when we try to run a codemod:
```
npx @cambly/syntax-codemods
Need to install the following packages:
@cambly/syntax-codemods@0.1.0
Ok to proceed? (y) y
node:internal/modules/cjs/loader:1042
throw err;
^
Error: Cannot find module 'jscodeshift/src/Runner'
```

Codemods: make jscodeshift a dependency

---

.changeset/empty-cups-grow.md
packages/syntax-core/src/Button/Button.module.css
packages/syntax-core/src/Button/Button.tsx

Button: update border styles for secondary + destructive secondary.

---

.changeset/sour-lobsters-explain.md
packages/syntax-core/src/RadioButton/RadioButton.module.css
packages/syntax-core/src/RadioButton/RadioButton.stories.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/useFocusVisible.test.tsx
packages/syntax-core/src/useFocusVisible.tsx

This solves the "use focus styling only when user uses keyboard to select components" rather than using the focus styling when using both keyboard and the mouse cursor
- added in useFocusVisible (from https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/useFocusVisible.js)
- added in tests for useFocusVisible
- added in `name` field to radio button for proper grouping
- simplified styling for radio button

[gp-2242] add in usefocusvisible, use in radiobutton

---

.changeset/twelve-hotels-approve.md
packages/syntax-core/src/Divider/Divider.test.tsx
packages/syntax-core/src/Divider/Divider.tsx

Allow `key` to be set as a prop on `<Divider />`
Any React component should accept `key` as a prop, otherwise we always have to wrap it if we use it in a list

Divider: allow key to be set as a prop

---

.changeset/eighty-socks-drive.md
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Button/Button.module.css

For certain languages, the text inside of `Button` was stacking. Adding flex-shrink 0 fixes the issue
Before:
After:

Box: Add flex-shrink

---

.changeset/fuzzy-foxes-smile.md
packages/syntax-core/src/Box/Box.test.tsx
packages/syntax-core/src/Box/Box.tsx

Pass through `role` attribute on `Box`
Helps with `Box` adoption and ensuring we have all accessibility attributes available

Box: pass through 'role' attribute

---

.changeset/soft-dryers-tease.md
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-core/src/Typography/Typography.tsx

This PR adds a `lineClamp` property to `Typography` to allow us to truncate the text at a specified number of lines

Typography: Add lineClamp

---

.changeset/quick-steaks-switch.md
packages/syntax-core/src/Box/Box.test.tsx
packages/syntax-core/src/Box/Box.tsx

Allow a `ref` to be set on `<Box />`
Increase `Box` adoption - currently folks are using a regular `div` whenever they have to set a `ref`

Box: forward ref

---

.changeset/perfect-dodos-call.md
packages/syntax-core/src/Box/Box.module.css
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Box/Box.tsx

* Remove `flexShrink` property on `<Box />`
* Introduce `flex` property on `<Box />`
* Add example to showcase the new property
* If we previously did `flexShrink={0}`, we should now use `flex="none"` instead
* This is a breaking change so we'll need to make changes in Cambly-Frontend when performing the Syntax upgrade

Box: remove flexShrink property and introduce flex property instead

---

.changeset/two-garlics-appear.md
packages/syntax-core/src/Button/Button.test.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/Checkbox/Checkbox.test.tsx
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/IconButton/IconButton.test.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/RadioButton/RadioButton.test.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/SelectList/SelectList.test.tsx
packages/syntax-core/src/SelectList/SelectList.tsx
packages/syntax-core/src/SelectList/SelectOption.tsx

Add a consistent `data-testid` attribute to our current interactive elements
Makes it way easier to use these components in tests
SelectList previously set its test id to `select-list` but it was always the same an no way to override it

Button/Checkbox/IconButton/RadioButton/SelectList: add data-testid

---

.changeset/chilled-teachers-double.md
packages/syntax-core/src/SelectList/SelectList.tsx

There are some places where `SelectList` is used, but label isn't. (Like in the NonAuthNavBar).

SelectList: remove label as req'd prop

---

.changeset/moody-coats-cheer.md
packages/syntax-core/src/RadioButton/RadioButton.module.css
packages/syntax-core/src/RadioButton/RadioButton.tsx

button was not clickable when z-index is customized

RadioButton declare div before input. Fixes bug when place in a HOC with customized z-index

---

.changeset/fluffy-scissors-sit.md
packages/syntax-core/src/SelectList/SelectList.module.css
packages/syntax-core/src/SelectList/SelectList.tsx

* SelectList: add `stopPropagation` on `onClick` to prevent an issue we on our Cambly landing pages on smaller screens
* SelectList: doc fixes
* SelectList: fix misspelling
Popover automatically closes when you click the select list, preventing you from selecting a language
https://github.com/Cambly/syntax/assets/127199/ea4251a2-3933-4e43-8d4c-261b92cd5007
Popover doesn't close when you click the select list, so you can select a language
https://github.com/Cambly/syntax/assets/127199/29c071a5-5a96-4d7d-a115-7a616d5003af

SelectList: stopPropagation onClick + doc fixes

---

.changeset/perfect-eyes-listen.md
packages/syntax-core/src/Checkbox/Checkbox.module.css
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/RadioButton/RadioButton.module.css
packages/syntax-core/src/RadioButton/RadioButton.tsx

* Update disabled states for `Checkbox` and `RadioButton`
* `RadioButton` fix spacing between label and radio button - always set it to 8px
Before it was really hard to see whether a Checkbox or RadioButton was disabled

Checkbox/RadioButton: update disabled states

---

.changeset/tame-knives-fold.md
packages/syntax-core/src/Avatar/Avatar.tsx
packages/syntax-core/src/Badge/Badge.tsx
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/ButtonGroup/ButtonGroup.tsx
packages/syntax-core/src/Card/Card.tsx
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/Divider/Divider.tsx
packages/syntax-core/src/Heading/Heading.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/MiniActionCard/MiniActionCard.tsx
packages/syntax-core/src/Modal/Modal.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/SelectList/SelectList.tsx
packages/syntax-core/src/Typography/Typography.tsx
packages/syntax-floating-components/src/Tooltip/Tooltip.tsx

Add a link to the storybook for each component
Make it way easier to navigate to the docs for a specific component

Docs: add individual links to each component

---

.changeset/nine-queens-pull.md
packages/syntax-core/src/TextField/TextField.module.css
packages/syntax-core/src/TextField/TextField.stories.tsx
packages/syntax-core/src/TextField/TextField.test.tsx
packages/syntax-core/src/TextField/TextField.tsx
packages/syntax-core/src/index.tsx

Add the `TextField` component which currently lives in `Cambly-Frontend`

TextField: add component

---

.changeset/curly-mirrors-dress.md
.github/actions/setup/action.yml
.github/workflows/release.yml
.npmrc
package.json
pnpm-lock.yaml

This PR uses the `engines` field in `package.json` and the `engine-strict` config in `.npmrc` to force the usage of `pnpm` in this repo.   It will throw an error if `npm` is used.
Please note:  this rewrote the lockfile when `pnpm install` was run again
Note: `packageManager` field in `package.json` is for [corepack](https://nodejs.org/api/corepack.html) usage, which is experimental node feature that has to be opted into.  That could be useful for us to explore longterm.

force pnpm usage

---

.changeset/fluffy-masks-invite.md
packages/syntax-core/src/Button/Button.test.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/IconButton/IconButton.tsx

Button / IconButton: make onClick optional
See `Button` test - it allows for a `Button` with `type="submit"` to submit a form

Button / IconButton: make onClick optional

---

.changeset/large-turtles-greet.md
packages/syntax-core/src/Button/Button.module.css
packages/syntax-core/src/Checkbox/Checkbox.module.css
packages/syntax-core/src/IconButton/IconButton.module.css
packages/syntax-core/src/RadioButton/RadioButton.module.css
packages/syntax-core/src/SelectList/SelectList.module.css

Updates the opacity for interactive elements from 30% to 50%
Regular
Before disabled
After disabled

Button/RadioButton/Checkbox/SelectList/IconButton: update disabled opacity

---

README.md
package.json

Require pnpm 8.6.6 or larger to avoid deprecation warning
```
pnpm i -g pnpm@8.6.0
WARN  deprecated pnpm@8.6.0: This version contains a regression. Upgrade to v8.6.2 or newer
```
More context: https://github.com/pnpm/pnpm/releases/tag/v8.6.2

Internal: require pnpm 8.6.6 or larger to avoid deprecation warning

---

.changeset/shaggy-panthers-mate.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

Make `"gray200"` a valid `color` for `<Badge />`
Working on implementing a design for a new `<LessonSchedulingRep />`:
https://www.figma.com/file/Y9IVAFSurWopQ7d6O2ucdx/Lesson-Rep?node-id=49%3A3791&mode=dev
The badge denoting a Private lesson is light gray with dark text.
After:

Feat: Badge color="gray200"

---

.changeset/wise-tips-live.md
packages/syntax-core/src/LinkButton/LinkButton.module.css
packages/syntax-core/src/LinkButton/LinkButton.stories.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx

Missing rel prop for best practices.
Depending on the discussion on what happens re: `camblystrap` overriding css for `LinkButton` as well, might need a `!important`, but waiting on that to merge this.

LinkButton: add rel prop for best practices

---

.changeset/fresh-years-beam.md
packages/syntax-core/src/Button/Button.module.css
packages/syntax-core/src/IconButton/IconButton.module.css
packages/syntax-core/src/IconButton/IconButton.tsx

- `<IconButton />` and `<Button />` have the same borders
- `"secondary"` + `"destructive-secondary"`
- border-colors changed from `700` -> `300` to match Figma
https://www.figma.com/file/p7LKna9JMU0JEkcKamzs53/%F0%9F%93%90-Syntax?node-id=1186%3A3565&mode=dev
https://www.figma.com/file/p7LKna9JMU0JEkcKamzs53/%F0%9F%93%90-Syntax?node-id=1342%3A3040&mode=dev

Patch button border colors + apply to IconButton

---

.changeset/metal-beds-end.md
packages/syntax-core/src/Badge/Badge.module.css
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

This PR adds an `icon` prop to `<Badge />`.
- ex: `<Badge icon={RestartIcon} text="Restart" />`
It allows for the rendering of an IconComponent before badge text string
@somethiiing your comment [here](https://github.com/Cambly/Cambly-Frontend/pull/6084#discussion_r1279202650) helped me decide how to implement this 🙏 🙏 
The design I am implementing calls for an Icon displayed in a Badge:  https://www.figma.com/file/Y9IVAFSurWopQ7d6O2ucdx/Scheduling-Rep?node-id=159%3A6571&mode=dev
Screenshots:
Badge in figma:
syntax storybook:

Feat: `<Badge icon={IconComponent} />`

---

.changeset/long-dots-cheer.md
packages/syntax-core/src/Badge/Badge.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx

Enables us to start using custom icons - not just material UI icons

Make className optional on icons

---

packages/syntax-core/src/Badge/Badge.module.css
packages/syntax-core/src/Badge/Badge.tsx

@christianvuerings , this PR is following up on your review comments from here:
https://github.com/Cambly/syntax/pull/213#discussion_r1282411980
https://github.com/Cambly/syntax/pull/213#discussion_r1282414338
- met with @ajmooo  to discuss the 14px line-height I added in + background on why
- when seeing the issue, decision was to reduce icon size to 12px
- with that, the badges stay the same height regardless of whether it is displaying an icon or not (this was the original issue that prompted the margin-hack in https://github.com/Cambly/syntax/pull/213
Figma links with the updates:
https://www.figma.com/file/p7LKna9JMU0JEkcKamzs53/%F0%9F%93%90-Syntax?node-id=5903%3A6371&mode=dev
https://www.figma.com/file/p7LKna9JMU0JEkcKamzs53/%F0%9F%93%90-Syntax?node-id=3954%3A11320&mode=dev

Badge: remove explicit line-height, decrease icon size to 12px

---

.changeset/heavy-moons-report.md
packages/syntax-core/src/IconButton/IconButton.tsx

**BREAKING CHANGE!**
Make accessibilityLabel required on `IconButton`
Enforces every IconButton to have a correct accessibility label
Avoids issues like this:

IconButton: make accessibilityLabel required

---

.changeset/popular-pots-attend.md
packages/syntax-core/src/Avatar/Avatar.module.css

Discussion is in [this slack](https://cambly.slack.com/archives/C033ZPY5M46/p1691699159828119)
Background set to black for this screenshot for clarity
As AJ noted, the 1px should be an _internal stroke_ so the size shouldn't increase as a result of adding the white border. Inspected that they're the same as they were both - as an example, a medium-sized avatar is still 40px

Update Avatar to include a 1px white border

---

.changeset/serious-rockets-smell.md
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/Modal/Modal.tsx
packages/syntax-floating-components/src/Tooltip/Tooltip.tsx

Fixes an issue with generated docs not working as expected when we use `forwardRef`. Description for each prop and whether the prop is required was not showing up
Looked at the test cases in `react-docgen` which don't use a generic for `React.forwardRef`:
https://github.com/reactjs/react-docgen/pull/277/files#diff-de4b771f65b56eed28f15d85b12e65a9a94643474177ce33588e0ee63ec836edR5-R7
So the fix is to annotate the type again.

Docs: fix generated docs for forwardRef components

---

.changeset/tough-trees-laugh.md
packages/syntax-core/src/Heading/Heading.test.tsx
packages/syntax-core/src/Heading/Heading.tsx
packages/syntax-core/src/Typography/Typography.test.tsx
packages/syntax-core/src/Typography/Typography.tsx

Allow `data-testid` to be set on `Typography` and `Heading`
Enables more intuitive and readable code that can be used for testing:
```tsx
// Before
<Heading>
<span data-testid="heading-testid">{heading}</span>
</Heading>
```
```tsx
// After
<Heading data-testid="heading-testid">
{heading}
</Heading>
```
* #157

Typography / Heading: allow data-testid to be set

---

.changeset/tender-pumpkins-scream.md
packages/syntax-core/src/LinkButton/LinkButton.test.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx

* `LinkButton` allow `ref` to be set
To avoid the following error when wrapping `LinkButton` in `NextLinkButton`:
```
1) [chromium] › adult-landing.spec.ts:17:7 › Adult landing › renders without warnings or errors in the console 
Error: Page rendered with console messages: error - Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?%s%s 
Check the render method of `ForwardRef(LinkComponent)`.
```
By using [forwardRef](https://react.dev/reference/react/forwardRef) on `LinkButton`
* #223 
* https://github.com/Cambly/Cambly-Frontend/pull/6276

LinkButton: allow ref to be set

---

generate-component/Template.test.tsx
generate-component/index.ts

no changeset because this doesnt require version bump, just utility
- update index function was commented out during testing, uncommenting it out now.
- update tests wording to be consistent with our current test wording

Generate Script: update script + test wording

---

.changeset/fifty-brooms-ring.md
packages/syntax-core/src/SelectList/SelectList.module.css

SelectList: avoid long text overlapping caret

SelectList: avoid long text overlapping caret

---

.changeset/quick-dots-breathe.md
packages/syntax-core/src/Chip/Chip.module.css

Chip is a clickable element and should have a cursor on hover. Adding `cursor: pointer` should fix this issue.
https://www.loom.com/share/14724ecbb04f499999bed4ed8b46374b

Chip: Update chip to have cursor on hover

---

.changeset/five-yaks-kneel.md
packages/syntax-core/src/LinkButton/LinkButton.module.css

LinkButton previously did not have `box-sizing: border-box` which was causing it to overflow (and not be centered) in certain places of the UI. Adding that should solve it.
Example: (note: this isn't live, just a demo)
BEFORE: 
AFTER:

LinkButton: Update box-sizing

---

.changeset/olive-kings-drop.md
packages/syntax-core/src/Box/Box.module.css
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/TapArea/TapArea.module.css
packages/syntax-core/src/TapArea/TapArea.stories.tsx
packages/syntax-core/src/TapArea/TapArea.test.tsx
packages/syntax-core/src/TapArea/TapArea.tsx
packages/syntax-core/src/index.tsx
packages/syntax-core/src/rounding.module.css

Adds the `TapArea` component to Syntax
We see more and more of a need of an accessible component which is clickable / tapable (to support mobile). Just grepping for `role="button"` in Cambly-Frontend shows 33 instances:
* The `compress` feature can happen in a follow up - I just added a base component that folks can start using today

TapArea: add component

---

.changeset/mean-seas-bake.md
packages/syntax-core/src/TapArea/TapArea.test.tsx
packages/syntax-core/src/TapArea/TapArea.tsx

Followup to https://github.com/Cambly/syntax/pull/246#discussion_r1329086735 because I need this behavior already.
We don't have this lint rule turned on to enforce this like we do in our frontend app, but as per accessibility specs, if it is visible and not a natively-interactable element type, it needs to handle keyboard events:
```
Visible, non-interactive elements with click handlers must have at least one keyboard listener.eslint[jsx-a11y/click-events-have-key-events](https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules/click-events-have-key-events.md)
```
Since we don't render this through a `<button />`, we need to handle keypress ourselves

Fix: TapArea - keyboard interaction when focused

---

.changeset/funny-dolls-know.md
packages/syntax-core/src/Modal/Layer.server.test.tsx
packages/syntax-core/src/Modal/Layer.test.tsx
packages/syntax-core/src/Modal/Layer.tsx

* Fixes `document is not defined` when server rendering `Layer`
* Add tests
@emmanuelgamboa09 raised the issue:
https://cambly.slack.com/archives/C04QEEZMSLF/p1695327506767059
First time we add a server test in Syntax, we should probably do this for other components as well
Failure in the test if we don't fix the issue:

Layer: fix document is not defined on SSR

---

.changeset/nine-apples-mate.md
packages/syntax-core/src/Heading/Heading.stories.tsx
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-core/src/Typography/Typography.tsx
packages/syntax-core/src/colors/colors.module.css

Adds the green / success color to `Typography` and `Heading`

Typography/Heading: add success/green color

---

.changeset/soft-rabbits-suffer.md
packages/syntax-floating-components/src/Tooltip/Tooltip.stories.tsx
packages/syntax-floating-components/src/Tooltip/Tooltip.tsx

https://cambly.atlassian.net/browse/GP-3127
Before: 
After:
I just added a floating portal to surround the tooltip dialogue box. 
I updated the default example to be a bit more complex and more similar to real world use case. 
A developer can look at the example and still be able to parse out the "copy pastable" code for tooltip

[gp-3127] add in floating portal so styles don't overlap the tooltip content box

---

.changeset/famous-lizards-melt.md
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Card/Card.tsx
packages/syntax-core/src/rounding.module.css

Also manually showed this to @ajmooo and he signed off on all of these
- update padding from 36px -> 28px on md + lg breakpoints
- update padding from 28px -> 20px on sm breakpoint
- update `xl` rounding from 32px to 24px

[SYN-13] Card styling updates + Box rounding change

---

.changeset/eleven-bulldogs-reflect.md
packages/syntax-core/src/Checkbox/Checkbox.module.css
packages/syntax-core/src/Checkbox/Checkbox.stories.tsx

Been looking into some tricky rendering issues with @kpatelPro over in our frontend repo.  after a long dive, we were able to trace the issue down to here.
Here's a video that of shows the issue with the storybook example I added with this PR, before the change in `Checkbox.module.css`
https://github.com/Cambly/syntax/assets/1890801/2896e7ba-f5a8-416f-85b3-7ad5a5f3f56c
I'm going to let @kpatelPro add more description in with this if he would like.

FIX: Checkbox: Fix input overlay rendering bug that forced way too much extra height in overflow containers

---

README.md

@ajmooo has created a document to act as a central source of truth for rules, dos/don'ts, and the status of implementations for different platforms.
This PR adds a link to that google doc to the README.md file at the root of this repo.

add link to syntax usage guidelines doc to repo's root README.md

---

.changeset/cold-bobcats-chew.md
packages/syntax-core/src/Button/Button.server.test.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/Checkbox/Checkbox.server.test.tsx
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/Chip/Chip.module.css
packages/syntax-core/src/Chip/Chip.server.test.tsx
packages/syntax-core/src/Chip/Chip.tsx
packages/syntax-core/src/IconButton/IconButton.server.test.tsx
packages/syntax-core/src/IconButton/IconButton.test.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/RadioButton/RadioButton.server.test.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/SelectList/SelectList.server.test.tsx
packages/syntax-core/src/SelectList/SelectList.tsx
packages/syntax-core/src/TapArea/TapArea.server.test.tsx
packages/syntax-core/src/TapArea/TapArea.tsx
packages/syntax-core/src/TextField/TextField.server.test.tsx
packages/syntax-core/src/TextField/TextField.tsx
packages/syntax-core/src/useIsHydrated.test.tsx
packages/syntax-core/src/useIsHydrated.tsx

When any of our interactive elements render it seems like they are immediately intractable, however since hydration hasn't happened yet, the initial state might get lost.
We toggle the hydration state globally and use that in our tests
https://github.com/Cambly/Cambly-Frontend/pull/6943
1. Doesn't solve the underlying issue - if a user immediately interacts without hydration being completed, we'll lose the initial state.
2. Requires extra hydration checks in all of our integration tests:
```tsx
await page.waitForSelector("[data-hydrated]");
await page.getByTestId("subscribe-button").click();
```
1. first render a disabled interactive element
2. load all the JavaScript
3. enable the interactive element once the JavaScript finished loading & running …

Interactive components: enable after hydration completes

---

.changeset/pretty-moose-punch.md
packages/syntax-core/src/TapArea/TapArea.module.css
packages/syntax-core/src/TapArea/TapArea.stories.tsx
packages/syntax-core/src/TapArea/TapArea.tsx

https://cambly.slack.com/archives/C033ZPY5M46/p1700070891891909?thread_ts=1699987244.953739&cid=C033ZPY5M46
Previously, when we hovered a TapArea which had a child with color, it would not show the TapArea hover style `rgba(0,0,0,0.1)`. The issue is that both the `Box` and `TapArea` components are trying to set the background.
Fixed it by adding a conditional child element which has the overlay style.
https://github.com/Cambly/syntax/assets/127199/a3eae106-ebbe-441b-add4-c1dd93acda43
https://github.com/Cambly/syntax/assets/127199/01f7fad9-4520-4999-b3e5-c536caf5fcab

TapArea: support hover on children with color

---

.changeset/neat-rats-deliver.md
packages/syntax-core/src/Button/Button.stories.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/IconButton/IconButton.stories.tsx
packages/syntax-core/src/colors/backgroundColor.ts
packages/syntax-core/src/colors/foregroundColor.ts
packages/syntax-core/src/colors/foregroundTypographyColor.ts
packages/syntax-core/src/constants.ts

As addressed in [this slack thread](https://cambly.slack.com/archives/C033ZPY5M46/p1700503376307279), we would like to add a "dark" IconButton. To expand that further from today's Syntax meeting, we should have this for Button as well.

Button/IconButton: add "inverse" color option to Button and IconButton

---

.changeset/mean-rats-love.md
packages/syntax-core/src/TapArea/TapArea.module.css
packages/syntax-core/src/TapArea/TapArea.stories.tsx
packages/syntax-core/src/TapArea/TapArea.test.tsx

Nest a link inside a `TapArea` and click it
Expected: link works as expected
Actual: link doesn't work
Root cause: [276](https://github.com/Cambly/syntax/pull/276) by @christianvuerings - we added an overlay which gets hit but none of the items inside the TapArea actually gets hit
Add `pointer-events: none` to the `TapArea`
https://github.com/Cambly/syntax/assets/127199/ca076b9f-2a3b-41f7-8552-cea29b31b7a7
https://github.com/Cambly/syntax/assets/127199/a9d0ba77-0718-49aa-8424-e206c57aff05

TapArea: fix issue with link nested in TapArea

---

.changeset/wise-apples-invite.md
packages/syntax-core/src/TextArea/TextArea.module.css
packages/syntax-core/src/TextArea/TextArea.server.test.tsx
packages/syntax-core/src/TextArea/TextArea.stories.tsx
packages/syntax-core/src/TextArea/TextArea.test.tsx
packages/syntax-core/src/TextArea/TextArea.tsx
packages/syntax-core/src/TextField/TextField.module.css
packages/syntax-core/src/TextField/TextField.stories.tsx
packages/syntax-core/src/TextField/TextField.tsx
packages/syntax-core/src/index.tsx

Adds `TextArea` component which previously lived in `Cambly-Frontend`
- Props: Add `data-testid`, `errorText`, `helperText`, `size` and `id` props
- Props: Make `maxLength` configurable and set default to 1024; 
- Props: Make `placeholder` optional, just as with `TextField`
- Test: Add client and server tests
- Documentation: Document each prop
- SSR support: Support Server Side Rendering by disabling the element before hydration
Also updated `TextField` so the font size + padding changes depending on the `size` - as defined in Figma.

TextArea: add component & update props

---

.github/workflows/dependency-review.yml

Enables https://github.com/actions/dependency-review-action to ensure we don't add new security vulnerabilities or packages with invalid licenses
Note that we will only be able to enable this on our private repos once we have [GitHub advanced security](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security) enabled
> [$49 per month per active committer.](https://resources.github.com/contact/security)

Add dependency review GitHub action

---

.changeset/pink-bees-promise.md
packages/syntax-core/src/Avatar/Avatar.tsx

Some svgs/icons have no background which makes it transparent on this. adding the white background handles this issue

Avatar: update background color on icon

---

.changeset/tasty-trees-walk.md
packages/syntax-core/src/RichSelect/RichSelectList.tsx

[Patch: RichSelectList -- selectTextValue arg type](https://github.com/Cambly/syntax/commit/7cac4a9aad35165df55b165098f7c0cc446df595)
- selectedTextValues could === "all"
- previous implementation would have called `selectTextValue(["a", "l", "l"])` in that case, likely leading to innaccurate text being displayed in the select trigger

Patch: `RichSelectList` type def for `selectTextValue` arg.  prevent innaccurate `selectTextValue(["a", "l", "l"])`

---

.changeset/cold-ads-love.md
packages/syntax-core/src/LinkButton/LinkButton.tsx

Hover styles are happening because theres no color set. This should fix that.

LinkButton: update color on LinkButton

---

.changeset/hungry-cups-warn.md
.vscode/extensions.json
packages/syntax-core/src/TapArea/TapArea.test.tsx
packages/syntax-core/src/TapArea/TapArea.tsx

In order to build custom accessible components we need to be able to access `onMouseEnter` and `onMouseLeave` on `TapArea`

TapArea: add onMouseEnter and onMouseLeave events

---

.changeset/angry-guests-call.md
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx

Follow up from #317 where I added `success-primary` and `success-secondary` but not `success-tertiary` to LinkButton and IconButton

LinkButton / IconButton: add success-tertiary as cambio options

---

.changeset/strange-pillows-repair.md
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/Heading/Heading.stories.tsx
packages/syntax-core/src/Heading/Heading.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/ThemeProvider/ThemeProvider.test.tsx
packages/syntax-core/src/ThemeProvider/ThemeProvider.tsx
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-core/src/Typography/Typography.tsx

Follow up to #317 which added a `ThemeProvider` and initial Cambio button styles. In this PR we add Cambio styles for `Typography` & `Heading`
* Typography/Heading: add Cambio options & styles
* Remove `elevation` when Cambio theme is selected
https://github.com/Cambly/syntax/assets/127199/ad63ee41-1e8f-4627-84d8-415f19edb3df

Typography/Heading: add Cambio options & styles

---

.changeset/seven-oranges-punch.md
tsup.config.ts

After adding hooks usage to `Typography` and `Heading` (because of Cambio theming), we see the following exception:
```
Error: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
```
Fix is to add `use client` to every exported file:

Add 'use client' to every Syntax component

---

.changeset/tasty-hornets-do.md
packages/syntax-core/src/Card/Card.test.tsx
packages/syntax-core/src/Card/Card.tsx

Follow up to https://github.com/Cambly/syntax/pull/258 which deprecated the `size` prop on `Card`

Card: remove deprecated size prop

---

.changeset/seven-candles-cry.md
packages/syntax-core/src/RichSelect/RichSelect.module.css
packages/syntax-core/src/RichSelect/RichSelectBox.tsx
packages/syntax-core/src/RichSelect/RichSelectList.stories.tsx
packages/syntax-core/src/RichSelect/RichSelectList.test.tsx
packages/syntax-core/src/RichSelect/RichSelectList.tsx
packages/syntax-core/src/SelectList/SelectList.module.css

This PR adds the following updates for RichSelectList:
- Make the `label` prop optional (similar to what we do for TextField
- Because the label is now optional, I've added a required `accessibilityLabel` prop
- Make the default color for the select box white
Changes needed for [Shoppable Group Lessons](https://www.figma.com/file/e0BhCuouCduwIhnB3D7NQc/Shoppable-Group-Lessons?node-id=170%3A35748&mode=dev) which is the first use case of RichSelectList

RichSelectList: update color and make label optional

---

.changeset/fluffy-files-press.md
packages/syntax-core/package.json
packages/syntax-core/src/Button/Button.stories.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/Chip/Chip.module.css
packages/syntax-core/src/Chip/Chip.stories.tsx
packages/syntax-core/src/Chip/Chip.tsx
packages/syntax-core/src/IconButton/IconButton.module.css
packages/syntax-core/src/IconButton/IconButton.stories.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/LinkButton/LinkButton.stories.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx
packages/syntax-core/src/colors/backgroundColor.ts
packages/syntax-core/src/colors/foregroundColor.ts

https://github.com/Cambly/syntax/assets/127199/9f0516d7-ae28-42f1-bca0-b9d116d7f85d

Button/IconButton/LinkButton: add 'on' lightBackground or darkBackground prop

---

.changeset/five-impalas-tan.md
packages/syntax-core/src/RichSelect/RichSelectList.tsx
packages/syntax-core/src/SelectList/SelectList.module.css

RichSelectList: fix classic & cambio styling

---

.changeset/honest-oranges-vanish.md
packages/syntax-core/src/index.tsx

Export the `useTheme` hook so we can use it in Cambly-Frontend

Syntax cambio: export useTheme

---

.changeset/stupid-tips-decide.md
packages/syntax-core/src/Typography/Typography.module.css

We should use `line-height: initial` for all of our Syntax text https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value
Noticed that we had a global line-height setting in Camblystrap.css which was setting this for all text on Cambly.com

Typography: set line-height to initial

---

.changeset/lucky-queens-draw.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Button/Button.module.css
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/colors/allColors.ts
packages/syntax-core/src/colors/colors.module.css

https://github.com/Cambly/syntax/assets/127199/b3827aa6-67f2-4942-9309-14a982ddeea0

Button/Badge: various Cambio updates

---

.changeset/serious-trees-yell.md
packages/syntax-core/src/RichSelect/RichSelectList.tsx

Passing in the onClick prop to the TapArea of RichSelectList never actually gets called since the mouse isn't clicking on that element. To trigger the onClick, it has to be passed into the div at the parent level.

RichSelectList: Update onClick call

---

.changeset/brown-dolphins-hug.md
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/ButtonGroup/Buttongroup.stories.tsx
packages/syntax-core/src/Card/Card.stories.tsx
packages/syntax-core/src/Checkbox/Checkbox.stories.tsx
packages/syntax-core/src/Heading/Heading.stories.tsx
packages/syntax-core/src/Modal/Modal.stories.tsx
packages/syntax-core/src/RadioButton/RadioButton.stories.tsx
packages/syntax-core/src/RichSelect/RichSelectBox.stories.tsx
packages/syntax-core/src/SelectList/SelectList.stories.tsx
packages/syntax-core/src/TapArea/TapArea.stories.tsx
packages/syntax-core/src/TextArea/TextArea.stories.tsx
packages/syntax-core/src/TextField/TextField.stories.tsx
packages/syntax-core/src/Tooltip/Tooltip.stories.tsx

Stories: add args where possible

---

.changeset/poor-maps-yawn.md
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx
packages/syntax-core/src/RichSelect/RichSelectList.tsx
packages/syntax-core/src/SelectList/SelectList.module.css
packages/syntax-core/src/SelectList/SelectList.tsx

LinkButton: show icons in Cambio

---

.changeset/soft-melons-yell.md
packages/syntax-core/src/Modal/FocusTrap.tsx

Noticed the following issue when using the Cambio theme: 
`Cannot read properties of undefined (reading 'focus')`
```tsx
var focusElement = (el) => {
if (typeof el.focus === "function") {
el.focus();
}
};
```
https://cambly-inc.sentry.io/issues/5098994999/?alert_rule_id=14792676&alert_type=issue&environment=production&notification_uuid=75afccdd-1d2a-42ce-97ea-d90d6d12c677&project=234235&referrer=slack

Modal: add extra focus element check

---

.changeset/ninety-rice-repair.md
packages/syntax-core/src/Modal/Modal.tsx

@zprong noticed that the `x` wasn't working on Cambio modals - this fixes that issue

Modal: fix close button in Cambio

---

.changeset/tough-cameras-grab.md
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-design-tokens/tokens/font/base.json

We currently use a trial version of the GT Super font which only supports a limited set of characters. That causes issues for our users and we should fix it.
* Use full version of GT super font (converted OTF => WOFF2 with https://cloudconvert.com/otf-to-woff2)
* Only use GT Super on supported languages
* Add Storybook example to show before / after

Typography: only use GT Super on supported languages

---

.changeset/blue-laws-lie.md
packages/syntax-core/src/Modal/Modal.stories.tsx
packages/syntax-core/src/Modal/Modal.tsx
packages/syntax-core/src/Typography/Typography.module.css

Updated so we use the font given to us by the foundry

Typography: use final font + Modal: fix image size

---

.changeset/weak-shirts-give.md
packages/syntax-core/src/Modal/FocusTrap.tsx
packages/syntax-core/src/Modal/Modal.module.css
packages/syntax-core/src/Modal/Modal.stories.tsx
packages/syntax-core/src/Modal/Modal.test.tsx
packages/syntax-core/src/Modal/Modal.tsx

Follow up from @somethiiing 's pr: https://github.com/Cambly/syntax/pull/364
* Remove magic numbers
* Fix focus on first item
* Scroll goes edge-to-edge
* Remove `classic` forking
https://github.com/Cambly/syntax/assets/127199/587669bb-0220-48e2-a564-dff24918e870

Modal: add scrollable functionality v2

---

.changeset/good-jokes-rescue.md
packages/syntax-codemods/package.json
packages/syntax-codemods/src/index.ts
packages/syntax-codemods/src/run-js-codeshift.ts
packages/syntax-codemods/src/transforms/__fixtures__/component-remove-prop/button-end-icon.input.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-remove-prop/button-end-icon.output.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-remove-prop/button-start-icon.input.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-remove-prop/button-start-icon.output.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-update-prop-value/avatar-size-xl.input.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-update-prop-value/avatar-size-xl.output.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-update-prop-value/box-rounding-xl.input.tsx
packages/syntax-codemods/src/transforms/__fixtures__/component-update-prop-value/box-rounding-xl.output.tsx
packages/syntax-codemods/src/transforms/__tests__/component-remove-prop.test.ts
packages/syntax-codemods/src/transforms/__tests__/component-update-prop-value.test.ts
packages/syntax-codemods/src/transforms/component-remove-prop.ts
packages/syntax-codemods/src/transforms/component-update-prop-value.ts
pnpm-lock.yaml

We currently have quite a few changes that we need to make to Syntax components across our whole app. Adding these generic components will make that migration easier.
List of future changes:
Adds codemods:
* `component-remove-prop` to remove a prop on a component
* `component-update-prop-value` to update the prop value of a component
```sh
npx @cambly/syntax-codemods -c component-remove-prop -p ~/cambly/Cambly-Frontend/src/ --component=Button --prop=startIcon
```
```sh
npx @cambly/syntax-codemods -c component-update-prop-value -p ~/cambly/Cambly-Frontend/src/ --component=Avatar --prop=size --previousPropValue=xl --nextPropValue=lg
```

Codemods: add component-remove-prop & component-update-prop-value

---

.changeset/serious-games-worry.md
packages/syntax-core/src/Avatar/Avatar.module.css
packages/syntax-core/src/Avatar/Avatar.stories.tsx
packages/syntax-core/src/Avatar/Avatar.tsx
packages/syntax-core/src/AvatarGroup/AvatarGroup.stories.tsx
packages/syntax-core/src/AvatarGroup/AvatarGroup.tsx
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/TapArea/TapArea.tsx

Changes to `Box` / `TapArea` / `Avatar` & `AvatarGroup` to remove / replace deprecated props
Related PR: https://github.com/Cambly/Cambly-Frontend/pull/9298

Box/Avatar/TapArea: remove deprecated props

---

.changeset/happy-bananas-switch.md

I forgot to commit the changeset to my LinkButton update PR, so it didn't trigger a version change

Add changeset for loading link button changes

---

.changeset/plenty-days-travel.md
packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/Box/Box.tsx
packages/syntax-core/src/Card/Card.tsx
packages/syntax-core/src/border.module.css

Note: since @christianvuerings is out for a week and he requested changes on my other PR (and so merging is blocked), I'm creating a new one so it isn't blocking my feature work. [original PR](https://github.com/Cambly/syntax/pull/381)
Talked with @christianvuerings + @ajmooo about how to handle this. we use this border prop fairly often. having a defined style makes it more consistent usage across the app. Also will eliminate usages of dangerouslySetInlineStyle just to set border

[Box] add optional border

---

.changeset/heavy-cougars-kick.md
packages/syntax-core/src/react-aria-utils/Triggerable.tsx

tooltip: update stylings to center trigger

---

.changeset/two-peas-sit.md
packages/syntax-icons/package.json

Current import has to be from the dist folder
`import Accent from "@cambly/syntax-icons/dist/Accent`
would love for us to be able to do it like 
`import Accent from "@cambly/syntax-icons/Accent"`

Icons: Add exports

---

packages/syntax-icons/package.json

removing the exports field in the packagejson

Icons: Revert package json change

---

.changeset/hot-boxes-happen.md
packages/syntax-core/src/Checkbox/Checkbox.module.css
packages/syntax-core/src/Checkbox/Checkbox.stories.tsx
packages/syntax-core/src/RadioButton/RadioButton.module.css
packages/syntax-core/src/RadioButton/RadioButton.stories.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/TextField/TextField.tsx

After we used Syntax on our Cambly settings page, we noticed a few missing props & bugs with responsive behavior
* `TextField`: add `maxLength`
* Checkbox: fix responsive behavior
* RadioButton: avoid setting a height + fix responsive behavior
Would be good to add e.g. a `CheckboxGroup` or `RadioButonGroup` in the future to make e.g. the spacing between items more consistent

Checkbox / RadioButton: fix responsiveness + TextField: add maxLength

---

.changeset/curly-shrimps-buy.md
packages/syntax-core/src/Checkbox/Checkbox.stories.tsx
packages/syntax-core/src/Checkbox/Checkbox.tsx
packages/syntax-core/src/RadioButton/RadioButton.stories.tsx
packages/syntax-core/src/RadioButton/RadioButton.tsx
packages/syntax-core/src/ariaProps.tsx

for https://axeauditor.dequecloud.com/test-run/de95ac14-f88c-11ee-a30d-2b2389e5f0d8/issue/07ac1b62-fc82-11ee-a631-135645ea1d04?sortField=ordinal&sortDir=asc&page=0&issuesCount=&searchKeyword=1724726&searchOn=id&row=0
the fix that deque recommends are:
I already recommended to @jennyhe1120 that she already do the second recommendation (add the fieldname to the error message), but since deque _strongly_ recommends the first option, i created this POC.
I created an ariaProps object that can be reused between the different inputs (checkbox/radio/textinput/etc), i only put `aria-describedby` for now, because that's the only one we need. other suggested ones are: `aria-label`, `aria-labelledby`, `aria-hidden` but concluded we didnt need them yet.
the other option was the just manually map the …

RadioButton/Checkbox: Add describedby as a prop

---

.changeset/itchy-cups-sparkle.md
packages/syntax-core/src/TextArea/TextArea.tsx

Noticed extra spacing above a `TextArea` when setting a custom label

TextArea: conditionally render label

---

.github/actions/setup/action.yml
.github/workflows/release.yml
README.md
package.json
pnpm-lock.yaml

Upgrades our package manager pnpm to `v9.0.4`
Run `npm install -g pnpm@9.0.4`
Had to use `9.0.4` instead of `9.1.1` because of this Vercel issue: https://github.com/vercel/vercel/issues/11607

Upgrade pnpm to latest version: v9.1.1

---

.changeset/breezy-singers-drop.md
packages/syntax-core/src/Badge/Badge.tsx

Add vertical padding to badge, so it looks better when mutiline
Before:
After:

[NOJIRA] Add vertical padding to badge

---

.changeset/funny-peas-learn.md
packages/syntax-core/src/TextField/TextField.stories.tsx
packages/syntax-core/src/TextField/TextField.tsx

Need step for this: https://www.figma.com/design/FDcPtWKnUQWY8VjVFhpjxe/Availability-filter?node-id=10699-17858&m=dev. So I added it.
Official documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step
I also fixed the other stories so they actually work:
Before:
After:

TextField: Add step param

---

.changeset/chatty-boxes-judge.md
packages/syntax-core/src/Tooltip/Tooltip.stories.tsx
packages/syntax-core/src/Tooltip/Tooltip.tsx

By default, on="lightBackground'. And if you want to use tooltip on a dark background, add on="darkBackground".

Tooltip: add on prop to adapt dark or white background

---

.changeset/rare-rocks-play.md
packages/syntax-core/src/RichSelect/RichSelectList.tsx

It's an [accessibility issue](https://axeauditor.dequecloud.com/test-run/de95ac14-f88c-11ee-a30d-2b2389e5f0d8/issue/612cdcd0-faf2-11ee-9650-4bcbd7c29630?sortField=ordinal&sortDir=asc&page=0&issuesCount=&searchKeyword=1722391&searchOn=id&row=0) that we don't flag the popover as a "menu" role. 
I believe adding `role="menu"` to the box within the Popover should solve this issue

RichSelectList: add menu role

---

.changeset/brave-adults-carry.md
packages/syntax-core/src/Badge/Badge.tsx
packages/syntax-core/src/Button/Button.stories.tsx
packages/syntax-core/src/Button/Button.tsx
packages/syntax-core/src/Button/constants/iconSize.ts
packages/syntax-core/src/Chip/Chip.tsx
packages/syntax-core/src/Icon/Icon.module.css
packages/syntax-core/src/Icon/Icon.stories.tsx
packages/syntax-core/src/Icon/Icon.tsx
packages/syntax-core/src/IconButton/IconButton.tsx
packages/syntax-core/src/LinkButton/LinkButton.stories.tsx
packages/syntax-core/src/LinkButton/LinkButton.tsx

Per a request from Joey and AJ, we're updating `Icon` sizing to be more like `Typography`. Will run a codemod in Cambly-FE after this is merged to update the sizing of our syntax icons

Icon: Update icon sizing

---

.changeset/four-grapes-protect.md
packages/syntax-core/src/Button/constants/iconSize.ts
packages/syntax-core/src/Icon/Icon.stories.tsx
packages/syntax-core/src/Icon/Icon.tsx

Small follow-up to the previous update. Noticed that the Icon scale as speced didnt exactly match the one with Typography (no size 0, default 300 instead of 200). Confirmed with design that we should update it to this.

Icon: Update sizing to match Typography scale

---

README.md
package.json

Noticed vercel builds were failing due to the following issue:
Fix by:
1. Upgrading to `pnpm@9.2.0`
2. Using corepack on vercel. More info at https://vercel.com/changelog/corepack-experimental-is-now-available

Fix pnpm deploy issue

---

.changeset/cold-wolves-play.md
packages/syntax-core/src/Tabs/TabLink.tsx
packages/syntax-core/src/Tabs/Tabs.stories.tsx

Noticed the following issue in VSCode:
> Property 'selectedTabDarkBackground' does not exist on type '{ tabContainerlightBackground: string; tabContainerDarkBackground: string; selectedTabOnLightBackground: string; selectedTabOnDarkBackground: string; unselectedTab: string; link: string; }'. Did you mean 'selectedTabOnDarkBackground'?
Note that this TS issue doesn't fail the build because of this outstanding TS ticket to support plugins during compilation:
* https://www.npmjs.com/package/typescript-plugin-css-modules#about-this-plugin
* https://github.com/microsoft/TypeScript/issues/16607
Also added a light / dark toggle to the `Tabs.Link` example so we can easily test:

Tabs.Link: fix selected state on=darkBackground

---

.changeset/yellow-lamps-leave.md
packages/syntax-core/src/IconButton/IconButton.module.css

these icon buttons should never shrink

IconButton: add flex none to prevent icon button from shrinking

---

.changeset/sharp-stingrays-sip.md
packages/syntax-core/src/TextArea/TextArea.tsx
packages/syntax-core/src/TextField/TextField.module.css
packages/syntax-core/src/TextField/TextField.tsx
packages/syntax-core/src/Typography/Typography.tsx
packages/syntax-core/src/colors/textColors.ts

TextArea/TextField error styling has too red of an error text. This pr changes the shade of the error text to `destructive700` from `destructive-primary` and changes the border thickness to 1px from 2px
Before:
After:
Relevant slack link: https://cambly.slack.com/archives/C06QK5KF3K4/p1716313519111459

TextArea/TextField: Fix error styling

---

.changeset/strange-eagles-relate.md
packages/syntax-core/src/Icon/Icon.tsx

- I noticed the sizes on the docstring didn't match with the actual styling: https://github.com/Cambly/syntax/blob/main/packages/syntax-core/src/Icon/Icon.module.css

Update icon sizes docstring and size types

---

.changeset/cuddly-kids-film.md
packages/syntax-core/src/Tabs/TabLink.tsx

From [this Cambly-Frontend PR](https://github.com/Cambly/Cambly-Frontend/pull/10554#discussion_r1653333648), a NextTabLink actually shouldn't require an href, because we feed it into next's `Link` component. 
LinkButton's href is also currently optional and I imagine it's for the same reason

TabLink: make href optional

---

.changeset/silly-kings-kiss.md
packages/syntax-core/src/Modal/Modal.tsx

Right now, if we hold click inside the modal and then drag and release click outside of the modal, we trigger the `onClick` on the backdrop div, which dismisses the modal. This update will only fire if the mouse down occurs on the backdrop and NOT when we release click on the backdrop.

Change onClick => onMouseDown

---

.changeset/clever-stingrays-boil.md

After [this PR](https://github.com/Cambly/syntax/pull/456), we don't accept 0 as an icon size

Bump syntax icons version

---

.changeset/few-phones-wash.md
packages/syntax-core/src/SelectList/SelectList.test.tsx
packages/syntax-core/src/SelectList/SelectList.tsx

We have an accessibility issue when using SelectList for opening a more complicated popover (example below). While clicking triggers the `onClick` function, we also need to trigger it if the user presses the "enter" or "space" key.

SelectList: call onClick when user presses enter or space key

---

.changeset/cool-buttons-rest.md
packages/syntax-core/src/Button/Button.module.css

As [noted](https://cambly.slack.com/archives/C033ZPY5M46/p1720803458912209) by Joey and AJ, our current hover, focus, and active states are barely noticeable for our primary light background or secondary dark background buttons since they're black and the linear gradient for those states is using black as the base color.
This PR updates the linear gradient for the background color of these states to use gray300 at 30% 
Before:
After:

Button: Update hover, focus, active opacity

---

.changeset/brown-turtles-fry.md
packages/syntax-core/src/Button/Button.module.css

The hover state for disabled buttons wasn't working as expected - it still looked like it was active with a pointer for the cursor and an animation on click. This PR updates the styling for disabled buttons to be non-interactive.
These stylings already work for focus and active since disabled buttons cannot have those states
Before:
https://github.com/user-attachments/assets/da8a63d7-008f-41ec-89b4-59201e53a82f
After:
https://github.com/user-attachments/assets/c9374cdf-8f47-40c3-9ac3-677eb9e3289c

Button: Update button disabled hover state

---

.changeset/hot-grapes-grow.md
packages/syntax-core/src/Tabs/TabButton.tsx
packages/syntax-core/src/Tabs/TabLink.tsx
packages/syntax-core/src/Tabs/Tabs.module.css

Context: https://cambly.slack.com/archives/C033ZPY5M46/p1720808650914279
The underline on the selected tab's margin is slightly off from design
Current:
Ideal:

Tabs: update underline css

---

.changeset/weak-grapes-jam.md
packages/syntax-core/src/Avatar/Avatar.tsx

[Figma](https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=6742-11605&t=gOMEsrWOzMgS3YzJ-0)
Per [this convo](https://cambly.slack.com/archives/C033ZPY5M46/p1721335898547979), icon sizes are too small currently on avatars -- this will at least fix the issue of the "online" icon being too small in our web app

Avatar: update icon sizes and layouts

---

.changeset/quick-tomatoes-peel.md

Updating Syntax runs into a type incompatibility -- this stems from changing Icon's `color` type [here](https://github.com/Cambly/syntax/pull/493). Each Icon in `syntax-icon` takes a `color` prop based on Icon's `color` prop. If we don't update the version there, each icon keeps the stale value of Icon's `color` prop 
https://app.circleci.com/pipelines/github/Cambly/Cambly-Frontend/63360/workflows/f0a49b47-78d5-46ed-bfa4-c70149bcb609/jobs/531312

Icons: bump version to update color prop type

---

.changeset/fluffy-spies-grin.md
packages/syntax-core/src/Icon/Icon.tsx
packages/syntax-core/src/colors/allColors.ts

Issue after [this PR](https://github.com/Cambly/syntax/pull/493) where IconButton color was appearing dark gray and the darkBackground field stopped working. 
Fixed by making the default color `inherit` for Icon

[NO-JIRA] Fix Icon Colors

---

.changeset/unlucky-squids-deliver.md
packages/syntax-core/src/Avatar/Avatar.tsx

I got the following specs wrong on the first iteration:
medium avatars should have a 16x16 icon with a lower offset 
small avatars should have a 12x12 icon instead of 10x10

Avatar: update icon sizes and offsets for medium and small variants

---

.changeset/clever-balloons-change.md
packages/syntax-core/src/ButtonGroup/ButtonGroup.module.css
packages/syntax-core/src/ButtonGroup/ButtonGroup.tsx
packages/syntax-core/src/ButtonGroup/Buttongroup.stories.tsx

Currently there are a few usages of ButtonGroup where the CTAs could be more responsive. Things will look normal on a desktop but then the mWeb view looks squished because CTAs are still side-by-side. Allowing ButtonGroup's orientation to be responsive should help alleviate most of those issues.
New props:
`smOrientation`
`lgOrientation`

ButtonGroup: Make orientation responsive

---

.changeset/tiny-bugs-deliver.md
packages/syntax-core/src/WordConfetti/WordConfetti.stories.tsx
packages/syntax-core/src/WordConfetti/WordConfetti.test.tsx
packages/syntax-core/src/WordConfetti/WordConfetti.tsx
packages/syntax-core/src/index.tsx

This PR implements a new component: [WordConfetti](https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=6797-14375&t=IumHj4TBoZL5jIyc-0)
Default: direction row with flex wrap
Default: column view
Extra long word: Confirmed with AJ and Casey that this is alright and okay for some cards to overlap slightly when tilted
Cool theme:
Warm theme:

WordConfetti: Implement new component

---

.changeset/red-turtles-look.md
packages/syntax-core/src/WordConfetti/WordConfetti.tsx

Noticed an error in the console when developing in Cambly-FE about the key in WordConfetto. Removed it as an actual prop and fixed the issue. Tested by looking at the console in the local storybook

WordConfetti: Fix WordConfetto key

---

.changeset/spicy-sheep-knock.md
packages/syntax-core/src/IconButton/IconButton.stories.tsx
packages/syntax-core/src/IconButton/IconButton.test.tsx
packages/syntax-core/src/IconButton/IconButton.tsx

Background:
As part of the [Next NavBar project](https://www.figma.com/design/W3Qpau7j62wblnK7xIwJDV/%F0%9F%A7%B0-IA-2024?node-id=607-12586&m=dev) I need to add an indicator to the `MessageButton` (`IconButton`). 
Changes:
- Add `indicatorColor `prop that is typed the same as `Box`'s `backgroundColor` that shows in the top right corner when it's passed in otherwise it doesn't show anything.
- Updated stories and tests
Screenshots:

[NOJIRA] Add indicatorColor prop to IconButton

---

apps/storybook/stories/Colors.tsx

Currently, you can't see white-40 and white-70 in storybook, and it's because the font color is white instead of black
Before:
After:

Update colors on storybook

---

.changeset/soft-garlics-allow.md
packages/syntax-core/src/TextField/TextField.stories.tsx
packages/syntax-core/src/TextField/TextField.test.tsx
packages/syntax-core/src/TextField/TextField.tsx

This idea/suggestion to add a [suffix](https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=3290-9971&m=dev) to `TextField` came up in the syntax meeting today. It's easy for us to add this so submitting this now. Will play around with a startBadge prop in another PR.
lightBackground:
darkBackground:
rtl:

TextField: Add endBadge prop

---

.changeset/small-apes-explode.md
packages/syntax-core/src/SelectList/SelectList.module.css
packages/syntax-core/src/SelectList/SelectList.stories.tsx
packages/syntax-core/src/SelectList/SelectList.tsx
packages/syntax-core/src/TextArea/TextArea.stories.tsx
packages/syntax-core/src/TextArea/TextArea.tsx
packages/syntax-core/src/TextField/TextField.module.css
packages/syntax-core/src/TextField/TextField.tsx

[SYN-79](https://cambly.atlassian.net/browse/SYN-79)
This PR accomplishes the following:
- updates text, border colors for lightBackground/darkBackground and selected states for `TextField`
- adds `on` prop to `TextArea` and `SelectList`
- updates stories for all three components
TextField lightBackground:
https://github.com/user-attachments/assets/e0b84d29-b767-49a9-a6ef-54b7ee6fbee8
TextField lightBackground error state:
https://github.com/user-attachments/assets/b32ca24b-fff6-4131-9a7b-1775fd9351da
TextField darkBackground and error state:
https://github.com/user-attachments/assets/0d7ac821-402f-41c9-890d-6e1043a4deb8
TextArea lightBackground and error state:
https://github.com/user-attachments/assets/1100ab15-81f6-4a13-af98-0255e797a7c8
TextArea darkBackground and error state: …

TextArea, SelectList: Add on prop and update lightBackground/darkBackground colors

---

.changeset/giant-actors-develop.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

Need yellow badge for [this design](https://www.figma.com/design/0X1OjuIrbLVso9L5Zzizyb/Cambio-Subscription-%2B-Checkout-Page?node-id=309-3880&t=5snBRTiQhTfEydvD-4)

Add yellow700 badge color

---

.changeset/shaggy-jars-hope.md
packages/syntax-core/src/Dialog/Dialog.module.css

[SYN-78](https://cambly.atlassian.net/browse/SYN-78)
Remove the outline from Dialog when it is launched (video is from Popover that uses Dialog):
https://github.com/user-attachments/assets/bb8ef56b-8fb9-4ff3-887b-8f69e2691dcc
[SYN-78]: https://cambly.atlassian.net/browse/SYN-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dialog: Remove outline

---

.changeset/wise-drinks-cheat.md
packages/syntax-core/src/Tabs/TabInternal.tsx

We have a UI issue with Tabs -- the hover state horizontal-padding is 0 which makes it look a bit ugly. This will fix that, but introduces another aesthetic issue, where the underline extends past the text. We've decided that this was fine, and is the better of two options
https://cambly.slack.com/archives/C033ZPY5M46/p1725925324938419
Before:
After:

Tabs: update hover state padding

---

.changeset/empty-beers-listen.md
packages/syntax-core/src/SelectList/SelectList.module.css
packages/syntax-core/src/SelectList/SelectList.tsx

There are some differences between select in Windows and Mac. On dark mode, if the background color is not set, it will cause the options container for select on Windows to have a default white background. Resulting in the inability to display white text. So we need to specify the background color for select

Fix selectList darkbackground error on windows

---

package.json
pnpm-lock.yaml

[Vitest VSCode extension](https://marketplace.visualstudio.com/items?itemName=vitest.explorer) requires at least 1.4.0. We are on 2.0.5
Example using the vitest extension in VSCode
https://github.com/user-attachments/assets/12014855-74a5-47c5-b4a2-2338cc4a4d44
* Since we don't change any runtime code, we don't need a changeset

Upgrade Vitest to latest version

---

.changeset/spicy-ladybugs-try.md
packages/syntax-core/src/WordConfetti/WordConfetti.test.tsx
packages/syntax-core/src/WordConfetti/WordConfetti.tsx

Follow up to https://github.com/Cambly/syntax/pull/556 with the following changes
1. Update tests so we deterministically determine the rotation & background color
2. Remove `useMemo` usage since we no longer perform 2 maps over the words array
3. Use `.length` instead of specific `3` or `5` number when getting the rotation & background color

WordConfetti: add simple hashing function (follow up)

---

.changeset/dry-berries-joke.md
packages/syntax-core/src/TapArea/TapArea.module.css
packages/syntax-core/src/TapArea/TapArea.test.tsx
packages/syntax-core/src/TapArea/TapArea.tsx

Just like we already have a `fullWidth` prop on `TapArea`, we should also have a `fullHeight`. It'll allow us to fix the following issue where we want the `height` of the items to be the same:

TapArea: add fullHeight prop

---

.changeset/healthy-news-enjoy.md
packages/syntax-icons/src/Icons.stories.tsx

Fix typo on identity document icon

---

.changeset/polite-crabs-shout.md
packages/syntax-core/src/Badge/Badge.tsx

Always capitalize text in badges 
https://cambly.slack.com/archives/C033ZPY5M46/p1727309871629329
Before:
After:

Badge: always capitalize text

---

.changeset/nervous-brooms-raise.md
packages/syntax-floating-components/src/Tooltip/Tooltip.stories.tsx
packages/syntax-floating-components/src/Tooltip/Tooltip.test.tsx
packages/syntax-floating-components/src/Tooltip/Tooltip.tsx
packages/syntax-floating-components/src/index.tsx

Update tooltip to have easier to use api
+ add zIndex as optional prop

Tooltip: update api + add zIndex as optional prop

---

.changeset/eleven-feet-knock.md
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx
packages/syntax-core/src/Typography/Typography.tsx

Add support to `Typography` component for setting white-space CSS property.

Allow option to preserve whitespace for Typography content

---

packages/syntax-core/src/Box/Box.stories.tsx
packages/syntax-core/src/colors/allColors.ts
packages/syntax-core/src/colors/colors.module.css

[Jira](https://cambly.atlassian.net/browse/WEB-5)
In dark mode, it makes it pretty clear which background colors are broken in syntax -- white40, white70, gray270:
The reason for this is because the `colors.module.css` file only had cambio class names for these e.g.
`.cambioWhite40`,`.cambioWhite70`, `.cambioGray270`
vs
`.white40`, `.white70`, `.gray270`
Because of this, the background color css lookup wasn't working because "white40" didn't map to any css classes.
After change: 
Question, should we get rid of all classes that start with `.cambio*`? And do we need to distinguish cambio specific colors in our `allColors.ts` file anymore? I don't think any of the cambio classes are being accessed anymore, so the css seems safe to remove? I can do that in a follow up PR

[WEB-5 SYNTAX] white40 updates

---

.changeset/soft-oranges-admire.md
packages/syntax-core/src/Tabs/TabInternal.tsx
packages/syntax-core/src/colors/textColors.ts

This change: https://github.com/Cambly/syntax/pull/584/files broke colors in a couple of places where components were referencing classes that no longer existed. I first noticed it when I saw the navbar on dark background (this is the tabs issue specificallly):
Repro'd  tabs in vercel preview:
After fix tabs:
Typography before with color "white-secondary":
Typography after with "white-secondary" fix:

[NOJIRA] Fix broken colors

---

.changeset/chatty-snails-reply.md
packages/syntax-core/src/RichSelect/RichSelectList.stories.tsx
packages/syntax-core/src/RichSelect/RichSelectList.tsx

Black Friday is about to begin and our tutor search page is broken:
Tested to see that it forwarded the z-index to the popover properly:
Needed a quick fix because black friday is beginning today. If you have a more robust fix in mind let me know.

[NOJIRA] Add option popoverZIndex prop to RichSelectList

---

.changeset/smart-clouds-love.md
packages/syntax-core/src/Typography/Typography.module.css
packages/syntax-core/src/Typography/Typography.stories.tsx

had an extra comma which applied to the wrong classes

Typography: Update css + reorganize css

---

.changeset/khaki-suits-burn.md
.github/workflows/ci.yml
.github/workflows/release.yml

> Artifact actions v3 will be deprecated by December 5, 2024. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://app.github.media/e/er?s=88570519&lid=6648&elqTrackId=d2da2b8a2e2546f6bbbefc4362a25248&elq=7714a0a4609d46bc95312d46f04f0c4d&elqaid=4245&elqat=1&elqak=8AF5A79567D1D842C6394C4E2A26BD2485A93AA4258C69BA5386AFF9B15AC8E8B20D) or [actions/download-artifact](https://app.github.media/e/er?s=88570519&lid=6647&elqTrackId=a0c373a95cb941a69247c326aef08dfe&elq=7714a0a4609d46bc95312d46f04f0c4d&elqaid=4245&elqat=1&elqak=8AF5A416F3461CA0C91DF8AF94CEC73EC20A3AA4258C69BA5386AFF9B15AC8E8B20D). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible …

Upgrade GitHub actions to v4

---

.changeset/twelve-llamas-call.md
packages/syntax-core/src/Chip/Chip.module.css
packages/syntax-core/src/Chip/Chip.stories.tsx
packages/syntax-core/src/Chip/Chip.tsx

[Figma](https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=676-10881&node-type=canvas&m=dev)
This PR adds a medium size to the Chip component. Previously we only had a small size which is now the default for this component.

[WEB-10] Chip: Add medium size

---

.changeset/new-pumas-relax.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

Figma: https://www.figma.com/design/7wAM5Us9AnFrYHyLV1YCEs/Premium-Tier?node-id=2023-6014&m=dev
Badge:
Adds silver colour for premium.
Text size should have been 0 instead of 100 here.

[NOJIRA] Badge: Add silver colour, change text size to 0

---

.changeset/warm-cobras-walk.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

In some spots, the individual badges are wrapped in a box which doesn't make the height the same, so tweak the padding. Original padding is 4px, but since this silver badge has a 1px border, make the paddingTop and paddingBottom be 3px
Before:
After:

Badge - silver: tweak padding

---

.changeset/spicy-baboons-brake.md
packages/syntax-core/src/RichSelect/RichSelectList.tsx

Allow people to access the RIchSelectItem if necessary when utilizing the rich select list component.

Allow RichSelectItem to be accessed from RichSelectList

---

.changeset/tidy-dodos-explode.md
packages/syntax-core/src/Button/Button.stories.tsx
packages/syntax-core/src/Icon/Icon.module.css
packages/syntax-core/src/Icon/Icon.stories.tsx
packages/syntax-core/src/Icon/Icon.tsx
packages/syntax-core/src/IconButton/IconButton.stories.tsx
packages/syntax-icons/src/icons/Accent.tsx
packages/syntax-icons/src/icons/ArrowLeft.tsx
packages/syntax-icons/src/icons/ArrowRight.tsx
packages/syntax-icons/src/icons/ChevronLeft.tsx
packages/syntax-icons/src/icons/ChevronRight.tsx
packages/syntax-icons/src/icons/Exit.tsx
packages/syntax-icons/src/icons/Help.tsx
packages/syntax-icons/src/icons/Play.tsx
packages/syntax-icons/src/icons/Progress.tsx
packages/syntax-icons/src/icons/Send.tsx
packages/syntax-icons/src/icons/UserRemove.tsx

Background
[As shown in the picture, the direction of the icon is reversed](https://docs.google.com/spreadsheets/d/1B_4adZJ4OMmywSMVuw5ry9deLe54_tW_BnbCQNh5QcQ/edit?gid=875673687#gid=875673687&range=7:7). This problem exists in many places.
At present, our project loads different icons by manually judging the document direction, which is not very convenient. I hope we don’t need to worry about this problem when using icons.
https://github.com/Cambly/Cambly-Frontend/blob/af479fc7a73c6c9fd26cbe5fed7e1c9121a2f72f/src/components/CamblychatTextMessages.jsx#L393
https://github.com/Cambly/Cambly-Frontend/blob/6f3a8dac657da5d730d5300865e0f48125278e74/src/components/GroupsSubscriptionPage/GroupsSubscriptionPageV2/GroupsSubscriptionPageV2.tsx#L50
My idea is to automatically mirror the icon if it is …

Icon: Add document direction support to Icon

---

.changeset/rich-days-turn.md
packages/syntax-core/src/Badge/Badge.stories.tsx
packages/syntax-core/src/Badge/Badge.tsx

blackandwhite - a black and white gradient
Example (ignore the yellow line; that was just a bad screenshot cut):

New badge color, used by Pro badge
