- .changeset/lemon-apricots-suffer.md
- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
For more information see https://github.com/changesets/action/issues/99
It ensures we can run actions on `Version Packages` PRs
It uses the https://github.com/camblybot account
> Internal: use GitHub PAT token for automation

- .changeset/sour-buses-rhyme.md
- packages/syntax-core/src/index.tsx
> Internal: Do not include CSS import in JS

- .changeset/smart-ghosts-shave.md
- packages/syntax-core/src/Button/Button.stories.tsx
- packages/syntax-core/src/Button/Button.tsx
- packages/syntax-core/src/ButtonGroup/ButtonGroup.tsx
- packages/syntax-core/src/ButtonGroup/ButtonGroupContext.tsx
- packages/syntax-core/src/ButtonGroup/Buttongroup.stories.tsx
- packages/syntax-core/src/colors/backgroundColor.ts
- packages/syntax-core/src/colors/foregroundColor.ts
- packages/syntax-core/src/constants.ts
> Internal: use array constants to show value on hover

- .changeset/serious-meals-drum.md
- packages/syntax-design-tokens/config.json
Example output
```kotlin
// Do not edit directly
// Generated on Tue, 28 Mar 2023 23:35:32 GMT
package StyleDictionaryColor;
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.*
object StyleDictionaryColor {
val colorBaseBlack = Color(0xff000000)
val colorBaseDestructive100 = Color(0xfffef3f5)
val colorBaseDestructive200 = Color(0xfffad6de)
val colorBaseDestructive300 = Color(0xfff2a2b2)
val colorBaseDestructive700 = Color(0xffd32a4b)
val colorBaseDestructive800 = Color(0xff81162c)
val colorBaseDestructive900 = Color(0xff55101d)
/** Used as the default color for dividers and inner strokes */
val colorBaseGray10 = Color(0x80cbcbcb)
val colorBaseGray100 = Color(0xfff7f7f7)
/** Used for light mode backgrounds when showing card content on top */
val colorBaseGray200 = …
```
> Design tokens: add Kotlin/compose output

- .changeset/fluffy-parrots-invent.md
- packages/syntax-core/src/Button/Button.module.css
reducing sm button corner radius from 12px to 8px
> Button: Update border radius for small button

- .changeset/green-beers-travel.md
- packages/syntax-core/src/RadioButton/RadioButton.module.css
- in hindsight, the radio button should have just been the radio button, not any text.
I'll put up a pr to fix that next week
> Update Radio Button styling for reusability

- .changeset/wild-spiders-admire.md
- package.json
- packages/syntax-codemods/.eslintrc.js
- packages/syntax-codemods/README.md
- packages/syntax-codemods/package.json
- packages/syntax-codemods/src/index.ts
- packages/syntax-codemods/src/run-js-codeshift.ts
- packages/syntax-codemods/src/transforms/__fixtures__/box-color-to-backgroundcolor/base.input.tsx
- packages/syntax-codemods/src/transforms/__fixtures__/box-color-to-backgroundcolor/base.output.tsx
- packages/syntax-codemods/src/transforms/__tests__/box-color-to-backgroundcolor.test.ts
- packages/syntax-codemods/src/transforms/box-color-to-backgroundcolor.ts
- packages/syntax-codemods/tsconfig.json
- packages/syntax-codemods/tsup.config.ts
- packages/syntax-core/src/Box/Box.stories.tsx
- packages/syntax-core/src/Box/Box.tsx
- pnpm-lock.yaml
Codemod: `npx . -c box-color-to-backgroundcolor -p ~/code/path`
> Box: convert color to backgroundColor

- .changeset/fast-seas-relax.md
- packages/eslint-config-syntax/package.json
- packages/syntax-codemods/package.json
- packages/syntax-core/package.json
- packages/syntax-design-tokens/package.json
- packages/syntax-tsconfig/package.json
- packages/syntax-utils/package.json
Helps with package discoverability
> Internal: add descriptions to package.json files

- .changeset/ten-rocks-type.md
- packages/syntax-codemods/src/transforms/__fixtures__/box-rounding-to-full/base.input.tsx
- packages/syntax-codemods/src/transforms/__fixtures__/box-rounding-to-full/base.output.tsx
- packages/syntax-codemods/src/transforms/__tests__/box-rounding-to-full.test.ts
- packages/syntax-codemods/src/transforms/box-rounding-to-full.ts
- packages/syntax-core/src/Box/Box.module.css
- packages/syntax-core/src/Box/Box.stories.tsx
- packages/syntax-core/src/Box/Box.tsx
Codemod: `npx @cambly/syntax-codemods -c box-rounding-to-full -p .`
> Box: convert rounding 'circle' and 'pill' to 'full'

- .changeset/curly-peaches-attack.md
- packages/syntax-core/src/SelectList/SelectList.test.tsx
- packages/syntax-core/src/SelectList/SelectList.tsx
Gray label, w/ red placeholder and error text
> Select list error state

- .changeset/brown-papayas-add.md
- packages/syntax-core/src/Checkbox/Checkbox.module.css
- packages/syntax-core/src/Checkbox/Checkbox.tsx
- packages/syntax-core/src/Focus.module.css
- packages/syntax-core/src/RadioButton/RadioButton.module.css
- packages/syntax-core/src/RadioButton/RadioButton.tsx
- packages/syntax-core/src/SelectList/SelectList.module.css
- packages/syntax-core/src/SelectList/SelectList.tsx
https://user-images.githubusercontent.com/31363881/233736962-39c46cd1-7c75-4b5e-af53-aadca58c97e0.mov
> add focus styling to checkbox select, consolidate focus styling

- .changeset/smooth-vans-smoke.md
- packages/syntax-core/src/colors/allColors.ts
- packages/syntax-core/src/colors/colors.module.css
- packages/syntax-design-tokens/tokens/color/base.json
> Add gray 60

- .changeset/early-carrots-protect.md
- packages/syntax-core/src/RadioButton/RadioButton.module.css
- packages/syntax-core/src/RadioButton/RadioButton.stories.tsx
scrolling bug I mentioned earlier (radioButton was scrolling with the window if it didn't have a positioned ancestor component )
also I was unintentionally being exclusionary
> [NOJIRA] scrolling bug

- .changeset/strong-balloons-compare.md
- packages/syntax-floating-components/src/Tooltip/Tooltip.stories.tsx
- packages/syntax-floating-components/src/Tooltip/Tooltip.tsx
Talked with AJ about setting the max width
> Add a max width to the tooltip

- .changeset/lemon-lies-obey.md
- packages/syntax-core/src/Button/Button.tsx
- packages/syntax-floating-components/src/Tooltip/Tooltip.stories.tsx
- packages/syntax-floating-components/src/Tooltip/Tooltip.tsx
https://github.com/Cambly/Cambly-Frontend/pull/5589#discussion_r1220519319
https://cambly.slack.com/archives/C04QEEZMSLF/p1686085562565099
Adding some minor changes we discussed
> [no-jira] type prop and default TooltipContent Typography

- .changeset/stale-ads-invite.md
- packages/syntax-core/src/Card/Card.stories.tsx
- packages/syntax-core/src/Card/Card.test.tsx
- packages/syntax-core/src/Card/Card.tsx
Add sizes + tests/stories for Card Component.
Small: 
Large:
> Card: Add sizes + update tests/stories

- .changeset/many-monkeys-build.md
- packages/syntax-core/src/SelectList/SelectList.tsx
Need to handle conditional div to center SelectList: (because of gap)
> SelectList: Handle conditional div 

- .changeset/unlucky-queens-rescue.md
- packages/syntax-core/src/SelectList/SelectList.test.tsx
- packages/syntax-core/src/SelectList/SelectList.tsx
@zprong noticed an issue in the `SelectListDate.tsx` component with the #174 PR. In that PR, we rely on the event being propagated since it looks like a `select` but is actually acting as a datepicker:
> SelectList: pass through onClick

- .changeset/warm-dots-add.md
- packages/syntax-core/src/SelectList/SelectList.module.css
- packages/syntax-core/src/SelectList/SelectList.tsx
* Adjust font sizes according to size
* Update font weight 
* Make label required
> SelectList: Adjust font sizes according to size + update font weight + make label required

- .changeset/yellow-turtles-breathe.md
- README.md
> Docs: add link to changeset documentation in README

- .changeset/tidy-beers-hammer.md
- packages/syntax-core/src/Modal/Modal.tsx
Per @kpatelPro 's suggestion [here](https://cambly.slack.com/archives/C033ZPY5M46/p1689730189668039?thread_ts=1688753475.234079&cid=C033ZPY5M46), added more descriptions to Modal for clarity.
> Modal: Update docs for clarity

- .changeset/three-goats-search.md
- packages/syntax-core/src/RadioButton/RadioButton.tsx
Just adding more types to `value` for Radio button
> [NOJIRA] Add in the accepted types that the primitive takes in

- .changeset/little-lies-drive.md
- packages/syntax-core/src/Heading/Heading.tsx
> Add line clamp to heading component

- .changeset/friendly-suns-clean.md
- packages/syntax-core/src/Card/Card.stories.tsx
- packages/syntax-core/src/Card/Card.tsx
Add the ability to change the background color on our cards
> Colored cards

- .changeset/tall-spies-pay.md
- packages/syntax-core/src/Modal/Modal.module.css
- packages/syntax-core/src/Modal/Modal.tsx
- packages/syntax-core/src/ThemeProvider/ThemeProvider.test.tsx
- packages/syntax-core/src/ThemeProvider/ThemeProvider.tsx
> Cambio: Modal & elevation updates

- .changeset/breezy-roses-rhyme.md
- packages/syntax-core/src/SelectList/SelectList.module.css
Brings it inline with what we use for TextArea / TextField
> Cambio SelectList: update font size

- .changeset/healthy-kangaroos-happen.md
- packages/syntax-core/src/Heading/Heading.tsx
> Heading: cambio updates

- .changeset/curvy-ways-warn.md
- packages/syntax-core/src/Modal/Modal.tsx
Update Close icon size from sm to md (20x20 to 48x48)
> Modal: Update size of Close (X) Icon on Modal from sm to md

- .changeset/brave-bears-wink.md
- packages/syntax-core/src/Badge/Badge.stories.tsx
- packages/syntax-core/src/Badge/Badge.tsx
- packages/syntax-core/src/Button/Button.tsx
- packages/syntax-core/src/Chip/Chip.stories.tsx
- packages/syntax-core/src/Chip/Chip.tsx
- packages/syntax-core/src/Heading/Heading.stories.tsx
- packages/syntax-core/src/LinkButton/LinkButton.tsx
- packages/syntax-core/src/Modal/Modal.stories.tsx
- packages/syntax-core/src/Modal/Modal.tsx
- packages/syntax-core/src/RichSelect/RichSelectList.stories.tsx
- packages/syntax-core/src/RichSelect/RichSelectList.tsx
- packages/syntax-core/src/SelectList/SelectList.stories.tsx
- packages/syntax-core/src/SelectList/SelectList.tsx
- packages/syntax-core/src/TextArea/TextArea.stories.tsx
- packages/syntax-core/src/TextArea/TextArea.tsx
- packages/syntax-core/src/TextField/TextField.stories.tsx
- packages/syntax-core/src/TextField/TextField.tsx
- packages/syntax-core/src/Typography/Typography.stories.tsx
- packages/syntax-core/src/Typography/Typography.tsx
- packages/syntax-core/src/colors/backgroundColor.ts
- packages/syntax-core/src/colors/border.ts
- packages/syntax-core/src/colors/foregroundColor.ts
- packages/syntax-core/src/constants.ts
Removes classic options on multiple components now that we shipped Cambio
- Badge: remove classic colors
- Chip / Modal / RichSelectList / SelectList / TextArea / TextField: remove size prop
- Typography: replace interactive => medium & heavy => regular weights
* https://github.com/Cambly/Cambly-Frontend/pull/9314
```
npx @cambly/syntax-codemods -c component-update-prop-value -p ~/cambly/Cambly-Frontend/src/ --component=Badge --prop=color --previousPropValue=gray200 --nextPropValue=gray370
npx @cambly/syntax-codemods -c component-update-prop-value -p ~/cambly/Cambly-Frontend/src/ --component=Badge --prop=color --previousPropValue=gray900 --nextPropValue=gray870
npx @cambly/syntax-codemods -c component-update-prop-value -p ~/cambly/Cambly-Frontend/src/ --component=Badge --prop=color …
```
> Badge / Chip / Modal / RichSelectList / SelectList / TextArea / TextField / Typography: Remove classic options

- packages/syntax-core/src/Button/Button.module.css
- packages/syntax-core/src/Button/Button.tsx
- packages/syntax-core/src/LinkButton/LinkButton.stories.tsx
- packages/syntax-core/src/LinkButton/LinkButton.tsx
Add loading state to LinkButton
> Add loading state to LinkButton

- .changeset/curvy-grapes-march.md
- packages/syntax-core/src/Typography/Typography.module.css
Design wants to change the line-height and letter spacing for GT super usage.
> Heading / Typography: set specific line-height and letter spacing for serif font

- .changeset/breezy-spoons-invite.md
- packages/syntax-core/src/Icon/Icon.tsx
- packages/syntax-icons/package.json
- packages/syntax-icons/src/Icons.stories.tsx
I was in the wrong directory when i `git add .` and didnt add the changeset
add auto copy import statement on icon click
> Icons: add changeset for 0.3.0

- .changeset/mean-lions-smash.md
- packages/syntax-core/src/SelectList/SelectOption.tsx
Add accessibility label for select options so screen reader can read it outloud
> SelectOption: add accessibility label

- .changeset/clever-trainers-march.md
- packages/syntax-core/src/Avatar/Avatar.module.css
- packages/syntax-core/src/Avatar/Avatar.stories.tsx
- packages/syntax-core/src/Avatar/Avatar.tsx
- packages/syntax-core/src/AvatarGroup/AvatarGroup.stories.tsx
- packages/syntax-core/src/AvatarGroup/AvatarGroup.tsx
add xl sizing to avatar + avatar group
> Avatar: Add xl size

- .changeset/rich-rocks-guess.md
- packages/syntax-core/package.json
increase memory size for build script
similar solution to our frontend knip problem: https://github.com/Cambly/Cambly-Frontend/blob/bcf887d3d3f6538fac0d5328923c833693e55e88/.github/workflows/knip.yml#L30
> Syntax: increase memory + fix build

- .changeset/quiet-hairs-worry.md
- packages/syntax-core/src/Modal/Modal.tsx
- packages/syntax-core/src/Tooltip/Tooltip.stories.tsx
JIRA: https://cambly.atlassian.net/browse/SYN-63?
This change has been made according to Cambio's design requirements
> Modal: Convert background color from white to gray100

- .changeset/nice-crews-jog.md
- packages/syntax-design-tokens/tokens/shadow/base.json
add shadow to design token
https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=6478-334&t=eaf3iqO614IAJAyz-0
> DesignTokens: add shadows to design token

- packages/syntax-core/src/Typography/Typography.module.css
size100: Line height = 150%
size200: Line height = 150%
size300: Line height = 140%
size400: Line height = 130%
> Typography: line spacing update

- .changeset/khaki-timers-hunt.md
- packages/syntax-core/src/Badge/Badge.stories.tsx
- packages/syntax-core/src/Badge/Badge.tsx
Needed for this [PR](https://github.com/Cambly/Cambly-Frontend/pull/10503#issuecomment-2192730896)
> [NOJIRA] Adding cream color for badge component

- .changeset/dirty-cobras-reflect.md
- package.json
- packages/syntax-core/src/Typography/Typography.module.css
- packages/syntax-core/src/Typography/Typography.stories.tsx
- packages/syntax-core/src/Typography/Typography.tsx
https://cambly.atlassian.net/browse/SYN-71
We want the following line heights when paragraph is specified.
size100: Line height = 150%
size200: Line height = 150%
size300: Line height = 140%
size400: Line height = 130%
> Typography: add paragraph type

- .github/workflows/release.yml
the release build needs this to auto merge
> Syntax: re-add pull request write

- .changeset/soft-tools-exist.md
- packages/syntax-core/src/Typography/Typography.module.css
- packages/syntax-core/src/Typography/Typography.stories.tsx
- packages/syntax-core/src/Typography/Typography.tsx
per cambio landing page, design wants an 800 size
> Typography: add size 800

- .changeset/heavy-camels-drop.md
- packages/syntax-core/src/SelectList/SelectList.module.css
- packages/syntax-core/src/SelectList/SelectList.stories.tsx
- packages/syntax-core/src/SelectList/SelectList.tsx
> SelectList: add clear color

- .github/workflows/release.yml
I think I made a mistake when requiring this, trying to delete this to see if it fixes our gh action
reverts: https://github.com/Cambly/syntax/pull/471
> Remove permissions line

- .changeset/thin-apricots-guess.md
- packages/syntax-core/src/Heading/Heading.stories.tsx
- packages/syntax-core/src/Heading/Heading.tsx
added size 800 to typography, but forgot to add to heading
> Heading: add size 800

- .changeset/popular-geckos-hug.md
- packages/syntax-core/src/RichSelect/RichSelectList.stories.tsx
- packages/syntax-core/src/RichSelect/RichSelectList.tsx
- packages/syntax-core/src/SelectList/SelectList.stories.tsx
- packages/syntax-core/src/SelectList/SelectList.tsx
> RichSelectList: add color prop from SelectList to fix styles

- packages/syntax-icons/package.json
- packages/syntax-icons/src/Icons.stories.tsx
- packages/syntax-icons/src/icons/Download.tsx
- packages/syntax-icons/svgs/download.svg
> Icons: Add download icon

- .changeset/neat-days-trade.md
- .changeset/tough-kiwis-buy.md
- packages/syntax-core/src/Icon/Icon.stories.tsx
- packages/syntax-core/src/Icon/Icon.tsx
- packages/syntax-core/src/colors/colors.module.css
https://cambly.atlassian.net/browse/SYN-73
> [SYN-73] Add all colors to Icon

- .changeset/lazy-moles-greet.md
- packages/syntax-core/src/Checkbox/Checkbox.module.css
- packages/syntax-core/src/Checkbox/Checkbox.tsx
- packages/syntax-core/src/RadioButton/RadioButton.module.css
- packages/syntax-core/src/RadioButton/RadioButton.tsx
[JIRA](https://cambly.atlassian.net/browse/SYN-74)
https://github.com/user-attachments/assets/b31c976a-828a-4456-a8c0-7f44b94b705f
https://github.com/user-attachments/assets/ab0f9bef-4d5f-4b4b-bf3e-98b71a30e583
> [SYN-74] RadioButton and CheckBox style updates to match Figma

- README.md
- package.json
Noticed builds were failing. Saw that christian did something similar here:https://github.com/Cambly/syntax/pull/445.
> [NOJIRA] Update pnpm to 9.4.0

- packages/syntax-icons/src/Icons.stories.tsx
Type issues with `Icon.Stories.tsx` due to the recent color changes.
https://github.com/user-attachments/assets/c5aac547-5164-4c1f-943c-c5d5a446c381
> [NO-JIRA] Fix Icon Stories bug

- .changeset/wise-planes-exist.md
- packages/syntax-core/src/Heading/Heading.tsx
- packages/syntax-core/src/Typography/Typography.module.css
- packages/syntax-core/src/Typography/Typography.stories.tsx
- packages/syntax-core/src/Typography/Typography.tsx
[Jira](https://cambly.atlassian.net/browse/SYN-77)
> Add size 500 typography

- .changeset/quiet-coats-raise.md
- packages/syntax-icons/package.json
- packages/syntax-icons/src/Icons.stories.tsx
- packages/syntax-icons/src/icons/ScreenOff.tsx
- packages/syntax-icons/svgs/screen-off.svg
Add a new "screen off" icon to be used in the classroom screenshare button
> [CORECLASS-1065] Add screen off icon

- .changeset/chilly-bulldogs-give.md
- packages/syntax-core/src/Button/constants/iconSize.ts
- packages/syntax-core/src/Icon/Icon.tsx
[SYN-80](https://cambly.atlassian.net/browse/SYN-80)'
Update the sizing for icons used in IconButton and Button
[SYN-80]: https://cambly.atlassian.net/browse/SYN-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Icon: Update icon size used for IconButton and Button

- .changeset/three-actors-doubt.md
- packages/syntax-core/src/Modal/Modal.tsx
[Jira ticket](https://cambly.atlassian.net/browse/SYN-82?atlOrigin=eyJpIjoiMjM2NjAzZDQzZTRmNDQ0NTg1OGUxY2I0YmVmNTk3N2MiLCJwIjoiaiJ9)
Change font size from 700 to 500
|before|after|
|---|---|
|<img width="503" alt="Screenshot 2024-10-15 at 2 00 07 PM" src="https://github.com/user-attachments/assets/9e558cdd-c54f-460a-86ec-a6bf57745c26"> | <img width="477" alt="Screenshot 2024-10-15 at 2 02 00 PM" src="https://github.com/user-attachments/assets/d8b3ca05-ea9d-4c6e-a033-28297ac6927a"> |
> Modal: update title size from to 500

- .changeset/swift-masks-swim.md
- packages/syntax-core/src/Toast/Toast.stories.tsx
- packages/syntax-core/src/Toast/Toast.test.tsx
- packages/syntax-core/src/Toast/Toast.tsx
- packages/syntax-core/src/index.tsx
[Figma](https://www.figma.com/design/G3UM2urgAYO2iiNU7nlulI/Cambio-Syntax?node-id=676-10881&node-type=canvas&m=dev)
This PR adds a new toast component to syntax
https://github.com/user-attachments/assets/d1ebf2f0-8d15-4c3d-994f-023edf5111da
> Toast: Add new component

- .changeset/hip-boats-eat.md
- packages/syntax-core/src/Button/Button.stories.tsx
- packages/syntax-core/src/Icon/Icon.module.css
- packages/syntax-core/src/Icon/Icon.stories.tsx
- packages/syntax-core/src/Icon/Icon.tsx
- packages/syntax-core/src/IconButton/IconButton.stories.tsx
- packages/syntax-icons/src/icons/Accent.tsx
- packages/syntax-icons/src/icons/ArrowLeft.tsx
- packages/syntax-icons/src/icons/ArrowRight.tsx
- packages/syntax-icons/src/icons/ChevronLeft.tsx
- packages/syntax-icons/src/icons/ChevronRight.tsx
- packages/syntax-icons/src/icons/Exit.tsx
- packages/syntax-icons/src/icons/Help.tsx
- packages/syntax-icons/src/icons/Progress.tsx
- packages/syntax-icons/src/icons/Send.tsx
- packages/syntax-icons/src/icons/UserRemove.tsx
Icons will be filpped in current version. To not affect other changes, revert it now.
> Revert f57e0c5
